name: BroKits-Insilicon-Test
version: '${version}'
main: dev.insilicon.brokitsinsilicontest.BroKits_Insilicon_Test
api-version: '1.20'
load: STARTUP
authors: [insilicon / ModdedKid]
description: Developer test for insilicon
commands:
  coinflip:
    description: Coinflip command
    usage: /coinflip
    aliases: [cf]
